# Copyright 2019 Pharmeum
# Developed by Highchain Software https://highchain.io/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2'

volumes:
  orderer.pharmeum.io:
  peer0.pharmeum.io:

networks:
  pharmeum:

services:
  ca.pharmeum.io:
    image: hyperledger/fabric-ca:1.4.1
    container_name: ca.pharmeum.io
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.pharmeum.io
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pharmeum.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/PHARMEUM_CA_PRIVATE_KEY
    ports:
      - 7054:7054
    expose:
      - 7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.pharmeum.io-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/PHARMEUM_CA_PRIVATE_KEY -b admin1:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/pharmeum.io/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - pharmeum

  orderer.pharmeum.io:
    container_name: orderer.pharmeum.io
    image: hyperledger/fabric-orderer:1.4.1
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=PharmeumOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/pharmeum.io/orderers/orderer.pharmeum.io/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/pharmeum.io/orderers/orderer.pharmeum.io/tls/:/var/hyperledger/orderer/tls
    ports:
      - 8050:7050
    networks:
      - pharmeum

  reserved_orderer.pharmeum.io:
    container_name: reserved_orderer.pharmeum.io
    image: hyperledger/fabric-orderer:1.4.1
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=PharmeumOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/pharmeum.io/orderers/reserved_orderer.pharmeum.io/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/pharmeum.io/orderers/reserved_orderer.pharmeum.io/tls/:/var/hyperledger/orderer/tls
    ports:
      - 9050:7050
    networks:
      - pharmeum

  pharmeum-couchdb:
    container_name: pharmeum-couchdb
    #TODO: set CouchDB version
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=$PHARMEUM_COUCHDB_USER
      - COUCHDB_PASSWORD=$PHARMEUM_COUCHDB_PASSWORD
    ports:
      - 5984:5984
    networks:
      - pharmeum

  peer0.pharmeum.io:
    container_name: peer0.pharmeum.io
    image: hyperledger/fabric-peer:1.4.1
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_pharmeum
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.pharmeum.io
      - CORE_PEER_ADDRESS=peer0.pharmeum.io:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pharmeum.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pharmeum.io:7051
      - CORE_PEER_LOCALMSPID=PharmeumMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=pharmeum-couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=$PHARMEUM_COUCHDB_USER
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=$PHARMEUM_COUCHDB_PASSWORD
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/pharmeum.io/peers/peer0.pharmeum.io/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/pharmeum.io/peers/peer0.pharmeum.io/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer.pharmeum.io
      - pharmeum-couchdb
    networks:
      - pharmeum

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.1
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.pharmeum.io:7051
      - CORE_PEER_LOCALMSPID=PharmeumMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pharmeum.io/peers/peer0.pharmeum.io/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pharmeum.io/peers/peer0.pharmeum.io/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pharmeum.io/peers/peer0.pharmeum.io/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pharmeum.io/users/Admin@pharmeum.io/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
#      - ./chaincodes/:/opt/gopath/src/github.com/chaincodes
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.pharmeum.io
      - peer0.pharmeum.io
    networks:
      - pharmeum
